# Generated by Django 3.1.2 on 2021-09-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.ImageField(upload_to='documents'),
        ),
    ]
