# Generated by Django 3.1.2 on 2021-10-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0002_auto_20210930_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
    ]
